# Generated by Django 5.1.4 on 2025-01-11 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renova_cycle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reward_images/'),
        ),
        migrations.AddField(
            model_name='rewardclaim',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('COLLECTED', 'Collecté')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='wastecontainer',
            name='capacity',
            field=models.FloatField(default=100.0, help_text='Capacité en kg'),
        ),
        migrations.AddField(
            model_name='wastecontainer',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='wastedeposit',
            name='waste_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wastecontainer',
            name='container_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='wastecontainer',
            name='current_fill_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='wastecontainer',
            name='last_emptied',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wastecontainer',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wastecontainer',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wastecontainer',
            name='waste_type',
            field=models.CharField(choices=[('ORGANIC', 'Organique'), ('NON_ORGANIC', 'Non-organique')], max_length=20),
        ),
    ]
