# Generated by Django 5.1.4 on 2025-01-11 23:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renova_cycle', '0002_alter_collectionpoint_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectiontask',
            options={'ordering': ['planned_date', 'status']},
        ),
        migrations.AddField(
            model_name='collectiontask',
            name='planned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectiontask',
            name='actual_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectiontask',
            name='collection_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='renova_cycle.collectionpoint'),
        ),
        migrations.AlterField(
            model_name='collectiontask',
            name='collector',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'COLLECTOR'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collectiontask',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='collectiontask',
            name='estimated_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectiontask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='collectiontask',
            name='waste_type',
            field=models.CharField(blank=True, choices=[('PLASTIC', 'Plastique'), ('METAL', 'Métal'), ('PAPER', 'Papier'), ('GLASS', 'Verre')], max_length=20, null=True),
        ),
    ]
