# Generated by Django 5.1.4 on 2025-01-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renova_cycle', '0003_alter_collectiontask_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiontask',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
