# Generated by Django 5.1.4 on 2025-01-12 15:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renova_cycle', '0004_collectiontask_started_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionrecord',
            options={'ordering': ['-collection_date']},
        ),
        migrations.RemoveField(
            model_name='collectionrecord',
            name='points_earned',
        ),
        migrations.AddField(
            model_name='collectionrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='collection_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='collector',
            field=models.ForeignKey(limit_choices_to={'user_type': 'COLLECTOR'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renova_cycle.collectiontask'),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='weight',
            field=models.FloatField(),
        ),
    ]
